// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEIdnnEl7G_SHxUrcHrClnPpaQP-KTtr8',
    appId: '1:855445397758:web:0ea46c75358a70bf34c5af',
    messagingSenderId: '855445397758',
    projectId: 'pet-compositive',
    authDomain: 'pet-compositive.firebaseapp.com',
    storageBucket: 'pet-compositive.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD849WuPMI_GiJ4rwGg-TCwBk2zK8swoNI',
    appId: '1:855445397758:android:2e96be19b8d55dac34c5af',
    messagingSenderId: '855445397758',
    projectId: 'pet-compositive',
    storageBucket: 'pet-compositive.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWsZt7xjWwHxt0_8W78lgnCFiV9Z2YYEc',
    appId: '1:855445397758:ios:124937c9b540b18634c5af',
    messagingSenderId: '855445397758',
    projectId: 'pet-compositive',
    storageBucket: 'pet-compositive.appspot.com',
    iosBundleId: 'com.example.flutterPracticeProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWsZt7xjWwHxt0_8W78lgnCFiV9Z2YYEc',
    appId: '1:855445397758:ios:124937c9b540b18634c5af',
    messagingSenderId: '855445397758',
    projectId: 'pet-compositive',
    storageBucket: 'pet-compositive.appspot.com',
    iosBundleId: 'com.example.flutterPracticeProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9wF3TuOXDt4DMksB9xFQUyw9N6AcgplA',
    appId: '1:855445397758:web:99744ccec8e8aa5434c5af',
    messagingSenderId: '855445397758',
    projectId: 'pet-compositive',
    authDomain: 'pet-compositive.firebaseapp.com',
    storageBucket: 'pet-compositive.appspot.com',
  );
}
